security:

    providers:
        our_db_provider:
            entity:
                class: App\Entity\Participants
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            provider: our_db_provider
            guard:
                authenticators:
                    - App\Security\LoginAuthenticator
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout_on_user_change: true
            logout:
                path: logout
                target: home

    encoders:
        App\Entity\Participants:
            algorithm: auto

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
